apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a53vfgwbr-go 
  janus-idp.io/tekton: a53vfgwbr-go
  backstage.io/kubernetes-id: a53vfgwbr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a53vfgwbr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  